### ISSUE TITLE
Make separate files with names of paths.

### ISSUE THREAD

**Issue by Kolyall** [alexjlockwood/ShapeShifter#132]
In generated file there are issue with Android:
"Element animated-vector doesn't have required attribute android:drawable. 'drawable' attribute should be defined. "

you can extract drawable `vector` and `objectAnimator` to separate files with names of path:
```
<animated-vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:drawable="@drawable/ic_PATH_NAME"
```

Can you add it as option to website as checkbox?

**Comment by alexjlockwood** [comment]
Yeah, I plan on creating some more detailed export options.

Note however that the error you are getting is an Android Studio bug (I reported it a few weeks ago and they are working on fixing it).

**Comment by alexjlockwood** [comment]
Closing because it looks like the Android Studio bug has been fixed in the latest canary. Feel free to reopen if you think it is still worth having.
