### ISSUE TITLE
AVD Export issue: [object Object]

### ISSUE THREAD

**Issue by vipulasri** [alexjlockwood/ShapeShifter#154]
I am having a problem while exporting the AVD.

In `objectAnimator` value of `android:valueFrom` and `android:valueTo` is coming as `[object Object]`.

```
<objectAnimator
      android:propertyName="pathData"
      android:duration="100"
      android:valueFrom="[object Object]"
      android:valueTo="[object Object]"
      android:valueType="pathType"
      android:interpolator="@android:anim/linear_interpolator"/>
```

**Comment by alexjlockwood** [comment]
Thank you for reporting! Really dumb bug on my part. I just published a fix... you might have to CMD + SHIFT + R the page to see a difference (in order to clear the cached version). LMK if you still have issues!
