### ISSUE TITLE
trimPathEnd animation will not export in SVG in the attached file

### ISSUE THREAD

**Issue by kgerontis** [alexjlockwood/ShapeShifter#157]
The file below is a compressed shapeshifter file which contains an animation of a molecular formula. It's not made to work as an icon but as an asset to be exported as animation for other uses. When exporting either as SVG or SVG spritesheet, the "trimPathEnd" animation is not exported and the paths are always fully drawn from frame zero till the end. Chrome v58 on Windows 10.

[epoxomicinBlack.zip](https://github.com/alexjlockwood/ShapeShifter/files/1094405/epoxomicinBlack.zip)

**Comment by alexjlockwood** [comment]
Yup, this is a known issue. Shouldn't be too hard to fix. Will try to get it working for the next release. :)

**Comment by alexjlockwood** [comment]
Actually, turns out the fix was really easy so I published a quick fix. Let me know if it works for you. Cool animation btw. :)

**Comment by kgerontis** [comment]
That was fast! Yes it works now, fantastic, thanks! And thanks for your comment, though the original image is taken from wikipedia, I just did the dirty job of manually tracing all line shapes to turn them to paths :)

**Comment by alexjlockwood** [comment]
:P 

BTW, clip-paths don't export to SVG yet either... but that is what I am planning on working on today. Just need to find some coffee first. :D
