### ISSUE TITLE
Add a canvas background color option

### ISSUE THREAD

**Issue by MaximilianKeppeler** [alexjlockwood/ShapeShifter#161]
When you work with opacity, stroke and fill color it can get a bit hard to work with the default white colored canvas background. Any idea from below would already work for me. 

- A simple toggle to switch to a predefined dark background 
- A color picker toggle to change the canvas background to any color (This would be cool, because you can take for example the background color of the view where the animation will be placed and check directly how it would look with the color combinations etc.)

**Comment by alexjlockwood** [comment]
Fixed in https://github.com/alexjlockwood/ShapeShifter/commit/bc11200d7adc48281b6c488367b8b6b81a1560d7

There will be a dark theme and a way to manually change the canvas background color in the next version. :)
