### ISSUE TITLE
Mouse Scroll Down is very slow

### ISSUE THREAD

**Issue by programadorthi** [alexjlockwood/ShapeShifter#178]
When we have a lot layers and we use the mouse scroll to see the layers below, the scroll is very slow.

We have to collapse other layers or resize the timeline window to see layers below.

I am using Chrome 59 and Windows 10.

**Comment by alexjlockwood** [comment]
Hi, thanks for reporting!

Do you mind sending an example SVG/shapeshifter file for me to test with? Would make it easier to fix. :)

**Comment by programadorthi** [comment]
Hi Alex,

I am testing the Heart Break demo. In my computer resolution, I can't see the filled layer.

**Comment by alexjlockwood** [comment]
What computer resolution are you using? Do you have a screenshot I could look at maybe?

**Comment by programadorthi** [comment]
I made a video. You can see in that link:

[Mouse Scroll is too slow](https://youtu.be/-OVWZuLl8Xk)

**Comment by alexjlockwood** [comment]
Perfect, thank you for the video! In the video are you scrolling the mouse wheel as fast as you can and it is still only scrolling that slowly?

**Comment by programadorthi** [comment]
Yes, I am. Is it normal scroll too slowly? Sorry if I reported like a issue!

**Comment by alexjlockwood** [comment]
No, that is definitely not supposed to happen! Sorry about that, I have never seen this before. Thanks for reporting, I'll try my best to reproduce the bug somehow!

**Comment by programadorthi** [comment]
I do not understand angular very well but I saw that you use scroll event to scroll both sides in the `scrollgroup.directive.ts` and keep sync. One more thing, thanks for the Shape Shifter. Amazing tool!

**Comment by alexjlockwood** [comment]
No problem. Glad you enjoy it. :)

I think I figured out the bug. I'll probably publish the next release on Monday so hope you don't mind waiting until then. You can check out the repo and run the tool locally too if you want (although there may be a couple of bugs... need to do some more testing... that's why I don't want to publish it right away. :)

**Comment by alexjlockwood** [comment]
I think this is fixed now?
