### ISSUE TITLE
Allow sorting subpath order

### ISSUE THREAD

**Issue by dalisoft** [alexjlockwood/ShapeShifter#182]
Allowing sorting subpath order gives better naturality, for more usecase i am use that method. Like always sort larger subpath first, then smaller

**Comment by alexjlockwood** [comment]
I believe there is already a way to do what you want: https://github.com/alexjlockwood/ShapeShifter/blob/master/src/app/model/paths/PathMutator.ts#L236

the `PathMutator#moveSubPath()` method allows you to move a subpath to a new position. For example, if you have a subpath with 4 subpaths `A B C D` and you do `moveSubPath(3, 1)` the result would be `A D B C` (i.e. move the subpath at index 3 to index 1).

**Comment by dalisoft** [comment]
I know that. But i am trying do it in GUI. So tried to get splitCommand and splitFilled/strokes command. Nothing i got. So i decided to use GUI

**Comment by alexjlockwood** [comment]
You can do this in the GUI as well. Just use the 'pair subpaths' option:

<img width="1920" alt="screen shot 2017-08-08 at 9 26 01 am" src="https://user-images.githubusercontent.com/1380747/29082823-a6d1aec6-7c1b-11e7-914b-5e9206d0b7a9.png">

**Comment by dalisoft** [comment]
Thanks
