### ISSUE TITLE
Cubify all command

### ISSUE THREAD

**Issue by dalisoft** [alexjlockwood/ShapeShifter#183]
* L->C
* A->C
* V->C
* H->C
* Q->C
* S->C
* T->C

This usecase is need for getting prepared paths for my tweening library.
This feature i am request for GUI, not JS

**Comment by alexjlockwood** [comment]
I don't think I'll get to this. Shape Shifter users don't need to care about the specific types of commands that are being used... they only care that the commands are converted into something that is in a compatible format and that can be morphed.

Are you sure your tweening library can't convert everything to cubic bezier curves instead?

**Comment by dalisoft** [comment]
No my tween lib just changes number
