### ISSUE TITLE
Preview disappears when working with groups

### ISSUE THREAD

**Issue by DarkionAvey** [alexjlockwood/ShapeShifter#189]
Hi
I'd like to report an issue. When I use scale animation with a fromValue that is less than 1, the preview disappears and the UI freezes.
Here's a video demonstrating the issue: 
http://darkion.net/Files/BugReport/shape_shifter_bug.mp4
The file I used:
http://darkion.net/Files/BugReport/test.xml

I've tried different browsers and got the same issue. 
Thanks!

**Comment by alexjlockwood** [comment]
Thanks for the detailed report! I'll take a look and see if it's an easy fix. Turns out I am rewriting large portions of this code (although it is still something I don't plan on releasing for at least a month or two).

**Comment by DarkionAvey** [comment]
Thanks for the prompt reply! Keep up the good work!

**Comment by alexjlockwood** [comment]
This no longer seems to be an issue... plesae let me know if you can still reproduce (because I can't... probably fixed a bug somewhere along the lines!).
