### ISSUE TITLE
Possible SVG import bug on transform

### ISSUE THREAD

**Issue by Karuma303** [alexjlockwood/ShapeShifter#193]
Hi Alex!

I might have found a possible bug in the SVG import.

Given this original simple SVG File:
```
<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160">
  <defs>
    <style>
      .a {
        fill: #ccc;
      }
    </style>
  </defs>
  <title>test</title>
  <g>
    <path class="a" d="M0.5,159.5V80A79.59,79.59,0,0,1,80,.5h79.5V80A79.59,79.59,0,0,1,80,159.5H0.5Z"/>
  </g>
</svg>
```

that is displayed (correctly) like this in ShapeShifter:

![1_original](https://user-images.githubusercontent.com/24876752/30973418-5878fff2-a46d-11e7-9a30-6ed824940120.png)

now, let's add some transformation to the path in the SVG to mirror it horizontally:
```
<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160">
  <defs>
    <style>
      .a {
        fill: #ccc;
      }
    </style>
  </defs>
  <title>test</title>
  <g>
    <path class="a" transform="translate(160) scale(-1, 1)" d="M0.5,159.5V80A79.59,79.59,0,0,1,80,.5h79.5V80A79.59,79.59,0,0,1,80,159.5H0.5Z"/>
  </g>
</svg>
```
Notice the translate and the scale commands here!

The result of this translation looks like this in ShapeShifter:

![2_mirrored](https://user-images.githubusercontent.com/24876752/30973429-5edf420c-a46d-11e7-8a18-f2e761394406.png)

That's not correct and in fact if you open up the second SVG file in any other tool it's perfectly mirrored.

So there might be an issue with the translation of some control points.

Here are two more pictures that show, how the control points look after the translation in ShapeShifter and how they should look like:

![3_shape_shifter](https://user-images.githubusercontent.com/24876752/30973433-6223118c-a46d-11e7-8dce-743a4c9d4fe5.png)

![4_should_be](https://user-images.githubusercontent.com/24876752/30973442-6533cc22-a46d-11e7-9276-d3b23b8548db.png)

Best, Kai

**Comment by alexjlockwood** [comment]
The issue also looks to be specific to the usage of elliptical arc commands... when I convert the path to cubic beziers, stuff works as expected: `M 0.5 159.5 L 0.5 80 C 0.55 36.114 36.114 0.55 80 0.5 L 159.5 0.5 L 159.5 80 C 159.45 123.886 123.886 159.45 80 159.5 L 0.5 159.5 Z`

**Comment by Karuma303** [comment]
Ah, good to know! Btw. the file was an export from Adobe Illustrator CC.

**Comment by alexjlockwood** [comment]
Filed here: https://github.com/svg/svgo/issues/803

**Comment by alexjlockwood** [comment]
Thanks again for filing, this will be fixed when I publish the next version of Shape Shifter (not entirely sure when that will be yet... some big stuff is in the works right now :P).

**Comment by Karuma303** [comment]
Thanks for the fix. Awesome project!
