### ISSUE TITLE
Don't crash app when importing @color/white etc. in Vector Drawables

### ISSUE THREAD

**Issue by alexjlockwood** [alexjlockwood/ShapeShifter#202]

**Comment by amilcar-andrade** [comment]
@alexjlockwood here is one example. I changed the extension to txt but the definition is the same. Just swap it back to xml
[play.txt](https://github.com/alexjlockwood/ShapeShifter/files/1392461/play.txt)

**Comment by alexjlockwood** [comment]
Oh, I think I figured out how to crash it. To reproduce:

1. Select the empty vector layer in the layer list.
2. Import the following SVG:

```
<svg width="1px" height="1px" viewBox="0 0 1 1" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <circle id="Oval" fill="#D8D8D8" cx="0.5" cy="0.5" r="1"></circle>
    </g>
</svg>
```

**Comment by amilcar-andrade** [comment]
Is there a workaround that I can do with my svgs? It seems I am seeing the same problem with the SVG icon instead of the vector drawable.

**Comment by alexjlockwood** [comment]
I think the workaround is to make sure nothing is selected in Shape Shifter before you attempt to import the SVG (i.e. nothing should be highlighted in blue in the layer list). Does that work?

**Comment by amilcar-andrade** [comment]
Let me check

**Comment by amilcar-andrade** [comment]
@alexjlockwood it actually works if nothing is highlighted. Maybe you can do a traversal with something like `element.focus(false)` whenever you tap on the import thing or something along those lines. Anyway, just a suggestion.

**Comment by alexjlockwood** [comment]
Yeah, I know what the issue is I think. Shouldn't be hard to fix. :)
