### ISSUE TITLE
it's possible to import it in android studio

### ISSUE THREAD

**Issue by akashcodechair** [alexjlockwood/ShapeShifter#206]
it's possible to import it in android studio
another wish which tool i should i use

**Comment by alexjlockwood** [comment]
Sorry, not sure what you mean. Could you be more specific?

If you click "Export" and then "Vector Drawable" or "Animated Vector Drawable", that will export an XML file that you should be able to use in an Android app (just copy the XML file into your `res/drawable` folder).

Check out this GitHub project for an example. I created many of the drawables in the project using Shape Shifter: https://github.com/alexjlockwood/adp-delightful-details
