### ISSUE TITLE
Any format that could be used to create animated icon sets for Android.

### ISSUE THREAD

**Issue by senseijtitus** [alexjlockwood/ShapeShifter#212]
Hi,

Is there any format that could be used to create animated icon sets for Android while the animations remain active even if the icons are integrated into Android UI or Launcher? .

**Comment by alexjlockwood** [comment]
Sorry, I'm not sure what you mean. Do you have an example in mind?

**Comment by alexjlockwood** [comment]
LMK if you have an example in mind.
