### ISSUE TITLE
android:fillType="evenOdd" is not exported

### ISSUE THREAD

**Issue by baobab2013** [alexjlockwood/ShapeShifter#217]
Import svg - > change fillType from nonZero to evenOdd -> Export VectorDrawable -> There's no android:fillType="evenOdd"

**Comment by alexjlockwood** [comment]
Hi, thanks for reporting the issue! Could you attach the `.shapeshifter` file you were using at the time when you encountered the bug? Thanks! (Just do File --> Save and attach the file to this bug report).

**Comment by alexjlockwood** [comment]
Just kidding, I think I see the issue. Will push a fix shortly.

**Comment by alexjlockwood** [comment]
Just published the fix. You might have to force refresh using `ctrl` + `shift` + `R` to see it. Thanks again!

**Comment by baobab2013** [comment]
Thank you for your quick response!
I checked that it's already fixed!
