### ISSUE TITLE
Rotated clip-path works even though it shouldn't...

### ISSUE THREAD

**Issue by IlToro** [alexjlockwood/ShapeShifter#221]
I have a rotated clip-path in my icon (meaning that it is inside a rotated group): it is still clipping/cutting items outside its parent in the animation preview but on Android AVD it doesn't because (as far as i know) it shouldn't.

**Comment by alexjlockwood** [comment]
Thanks for the report! Do you have an example SVG and/or shapeshifter project I could test? You can do "File" --> "Save" and then paste the exported `.shapeshifter` file to this report.

**Comment by IlToro** [comment]
@alexjlockwood 
Wow, I had JUST overwritten the old file, fortunately i found the old version in the recycle bin!
The problem is the shade below the graph: in ShapeShifter (great tool anyway) the shade works just fine cause the clip-path inside "group_clip_path" clips the outside its group. However in Android this will not happen cause it should not happen in SS either (i think it's a rule, [see here](https://stackoverflow.com/questions/36807351/can-android-drawables-clip-path-layer-be-rotated) )


[chart_final.txt](https://github.com/alexjlockwood/ShapeShifter/files/1609973/chart_final.txt)

**Comment by alexjlockwood** [comment]
That is a really cool animation! :)

And yes! Thank you for pointing this out, you're correct that clip-paths in Android are only meant to clip the items in their parent `<group>`. Fortunately, it was an easy fix on my end. I'll publish an update to https://shapeshifter.design within a few days!

**Comment by IlToro** [comment]
Thank you so much, you were so quick!
If you need the correct verion of the animation just ask me!

**Comment by alexjlockwood** [comment]
Just published an update... let me know if the bug is fixed for you!
