### ISSUE TITLE
Shapes gallery suggestion

### ISSUE THREAD

**Issue by kidwon24** [alexjlockwood/ShapeShifter#230]
Hi Alex,
may I say that your tool is great and very helpful.

May I suggest a gallery of animated vector to be provided in the live version for those of the users who want to share their animations?
With good search and tags and with converter to animated png for preview?
This would have great impact and would be of help to a lot of users.
Please consider it.

**Comment by alexjlockwood** [comment]
Good idea! I think this has already been filed here. I'm definitely considering it! https://github.com/alexjlockwood/ShapeShifter/issues/229
