### ISSUE TITLE
expandable chevron demo

### ISSUE THREAD

**Issue by joaosardinha** [alexjlockwood/ShapeShifter#233]
Hi!,

I was looking at the exapanding chevron that is exposed in the README as a .gif but not in the demos, is its source somewhere?

Thanks!

**Comment by alexjlockwood** [comment]
I think this was answered over slack?

**Comment by joaosardinha** [comment]
Maybe also post it here, so people who are not on slack can find it? :)

**Comment by alexjlockwood** [comment]
Did you end up making one?

**Comment by joaosardinha** [comment]
I did not, no
