### ISSUE TITLE
Bring back support for pasting SVG code rather than requiring you to use the Import menu

### ISSUE THREAD

**Issue by romannurik** [alexjlockwood/ShapeShifter#236]
I think(?) Android Icon animator allowed just <kbd>Cmd+V</kbd> with SVG text in your clipboard to import SVG... would be nice to support that :)

**Comment by alexjlockwood** [comment]
Yeah... I thought I had implemented this (and maybe even copied it from Android Icon Animator). If I did then I must have broken it at some point... -.-

**Comment by alexjlockwood** [comment]
Ughhhh the fact that I have no tests is stressing me out.

But yeah this should be fixed now... until the next time I break it at least.

Probably will release in the next week or so (I fixed a bunch of other bugs too).

paper.js release TBA. :D

**Comment by romannurik** [comment]
Heh, well thanks for the fix regardless!

**Comment by alexjlockwood** [comment]
Please file other feature requests/bugs if you think of any!

**Comment by alexjlockwood** [comment]
Also did your daughter turn 18 yet? Cause like, doesn't contributing an export-to-CSS-keyframes feature sound like so much fun? :D

**Comment by alexjlockwood** [comment]
Doesn't it look like so much fun? So much fancy math...

![img_20170815_214426 1](https://user-images.githubusercontent.com/1380747/38219393-4b1f1422-368a-11e8-9dc9-e8837d020316.jpg)

(Haven't actually started writing it yet though, lol).

**Comment by romannurik** [comment]
Haha, a CSS export may not be too bad... I can dig up some old code for that possibly

**Comment by alexjlockwood** [comment]
The real one I wanna do is export to bodymovin, but bodymovin format is so much to learn. :(
