### ISSUE TITLE
can't import svg twice

### ISSUE THREAD

**Issue by binggege** [alexjlockwood/ShapeShifter#241]
code:https://github.com/alexjlockwood/ShapeShifter/blob/master/src/app/components/layertimeline/layertimeline.component.ts#L1064

why do you execute `event.preventDefault()` when click  svg upload button once time ? 

![image](https://user-images.githubusercontent.com/5547743/38246326-027846c2-3774-11e8-99d5-df167ea750dd.png)

**Comment by alexjlockwood** [comment]
Is there a bug you are experiencing? If so, what is it?

Are you using the published version or are you building ShapeShifter locally on master or next branch?

**Comment by alexjlockwood** [comment]
Try removing event.preventDefault() and see what happens.

For me, without it the file picker dialog shows twice.

But is this causing a bug for you?

**Comment by binggege** [comment]
problem 1:
Use the latest version of chrome access `https://shapeshifter.design/ `，reference：
![bbb](https://user-images.githubusercontent.com/5547743/38280722-7ed54b1a-37d9-11e8-8bdf-e506db4b976c.gif)

**The File selection box appear twice， when I choice to import svg once**

problem 2:
Maybe I didn't make myself clear. I mean I use the master branch to have a test . I found that I can only import svg once. I check your code(https://github.com/alexjlockwood/ShapeShifter/blob/master/src/app/components/layertimeline/layertimeline.component.ts#L1064) ，I found you execute event.preventDefault() when click svg upload button once time. That's the cause of the problem 2. I try to annotation this code ，It's Ok now. I test by `npm run start`.

**Comment by alexjlockwood** [comment]
Ahh, I see. Thanks very much for reporting!

Can you try again on the latest `master` branch? The latest version at https://shapeshifter.design doesn't have the fix yet, but I am planning on publishing a new version within the next week or so.

**Comment by alexjlockwood** [comment]
OK, try again... I think I fixed it for real this time.

**Comment by binggege** [comment]
It's ok now(branch master) thx
