### ISSUE TITLE
Clip-path behavior on SVG keyframes

### ISSUE THREAD

**Issue by PrattiDev** [alexjlockwood/ShapeShifter#252]
Hi. I haven't used this tool in a while, so I might be unaware of some of the changes that were made, but when I came back, mostly if not all of my animations containing clip-paths got irreversibly broken.

That wasn't a big issue at the time, because the AVDs had already been implemented in the app I made them for. However, for the past hour I've been trying to fix one of my animations and nothing seems to work.

It contains 3 nested clipping masks that are supposed to be active all at once.  The problem is that the SVG(Edit: Not CSS) keyframes generated by Shapeshifter seem to ignore the other 2 clipping masks, making the animation impossible .Curiously, the Shapeshifter website previews them correctly, and the AnimatedVectorDrawable also works as intended. 

The reason I'm using multiple masks is because tweaking one specific shape wouldn't allow for different interpolators and other basic features a normal path/clipping path has.

Here's the Shapeshifter file: https://drive.google.com/open?id=1DBiTxJU2tfj50jFFbQv6X-OF48tSl8a_

**Comment by alexjlockwood** [comment]
Thanks for reporting! I haven't tested this in a while... could be I broke something accidentally.

Could you confirm the Google Drive URL you posted? I get a 404 not found when I try to view it.

**Comment by PrattiDev** [comment]
It appears Github ignored the underline at the end of the link. [Clicking here should work](https://drive.google.com/open?id=1DBiTxJU2tfj50jFFbQv6X-OF48tSl8a_)

But if it makes things easier, I'll also drop the code here.

{
  "version": 1,
  "layers": {
    "vectorLayer": {
      "id": "447",
      "name": "detail_expand_collapse",
      "type": "vector",
      "children": [
        {
          "id": "448",
          "name": "first_line",
          "type": "mask",
          "pathData": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9 11 L 7 11 L 7 9 L 9 9 Z"
        },
        {
          "id": "449",
          "name": "second_line",
          "type": "mask",
          "pathData": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 17 11 L 15 11 L 15 9 L 17 9 Z"
        },
        {
          "id": "450",
          "name": "third_line",
          "type": "mask",
          "pathData": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 13 11 L 11 11 L 11 9 L 13 9 Z"
        },
        {
          "id": "451",
          "name": "note_bubble",
          "type": "path",
          "pathData": "M 22 4 C 22 2.89 21.1 2 20 2 L 4 2 C 2.895 2 2 2.895 2 4 L 2 16 C 2 17.105 2.895 18 4 18 L 18 18 L 22 22 L 22 4 Z",
          "fillColor": "#000000"
        }
      ]
    },
    "hiddenLayerIds": []
  },
  "timeline": {
    "animation": {
      "id": "452",
      "name": "anim",
      "duration": 1600,
      "blocks": [
        {
          "id": "453",
          "layerId": "450",
          "propertyName": "pathData",
          "startTime": 0,
          "endTime": 50,
          "interpolator": "ACCELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 13 11 L 11 11 L 11 9 L 13 9 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9.5 11.5 L 7.5 11.5 L 7.5 9.5 L 9.5 9.5 Z"
        },
        {
          "id": "454",
          "layerId": "450",
          "propertyName": "pathData",
          "startTime": 50,
          "endTime": 75,
          "interpolator": "DECELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9.5 11.5 L 7.5 11.5 L 7.5 9.5 L 9.5 9.5 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 13.75 L 6.5 13.75 L 6.5 11.75 L 8.5 11.75 Z"
        },
        {
          "id": "455",
          "layerId": "450",
          "propertyName": "pathData",
          "startTime": 75,
          "endTime": 300,
          "interpolator": "DECELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 13.75 L 6.5 13.75 L 6.5 11.75 L 8.5 11.75 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 18 14 L 6 14 L 6 12 L 18 12 Z"
        },
        {
          "id": "456",
          "layerId": "449",
          "propertyName": "pathData",
          "startTime": 0,
          "endTime": 75,
          "interpolator": "ACCELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 17 11 L 15 11 L 15 9 L 17 9 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 11 L 6.5 11 L 6.5 9 L 8.5 9 Z"
        },
        {
          "id": "457",
          "layerId": "449",
          "propertyName": "pathData",
          "startTime": 75,
          "endTime": 185,
          "interpolator": "DECELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 11 L 6.5 11 L 6.5 9 L 8.5 9 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 18 11 L 6 11 L 6 9 L 18 9 Z"
        },
        {
          "id": "458",
          "layerId": "448",
          "propertyName": "pathData",
          "startTime": 0,
          "endTime": 30,
          "interpolator": "ACCELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9 11 L 7 11 L 7 9 L 9 9 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 8.5 L 6.5 8.5 L 6.5 6.5 L 8.5 6.5 Z"
        },
        {
          "id": "459",
          "layerId": "448",
          "propertyName": "pathData",
          "startTime": 30,
          "endTime": 135,
          "interpolator": "DECELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 8.5 L 6.5 8.5 L 6.5 6.5 L 8.5 6.5 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 18 8 L 6 8 L 6 6 L 18 6 Z"
        },
        {
          "id": "460",
          "layerId": "450",
          "propertyName": "pathData",
          "startTime": 800,
          "endTime": 1025,
          "interpolator": "ACCELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 18 14 L 6 14 L 6 12 L 18 12 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 13.75 L 6.5 13.75 L 6.5 11.75 L 8.5 11.75 Z"
        },
        {
          "id": "461",
          "layerId": "450",
          "propertyName": "pathData",
          "startTime": 1025,
          "endTime": 1050,
          "interpolator": "ACCELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 13.75 L 6.5 13.75 L 6.5 11.75 L 8.5 11.75 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9.5 11.5 L 7.5 11.5 L 7.5 9.5 L 9.5 9.5 Z"
        },
        {
          "id": "462",
          "layerId": "450",
          "propertyName": "pathData",
          "startTime": 1050,
          "endTime": 1100,
          "interpolator": "DECELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9.5 11.5 L 7.5 11.5 L 7.5 9.5 L 9.5 9.5 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 13 11 L 11 11 L 11 9 L 13 9 Z"
        },
        {
          "id": "463",
          "layerId": "449",
          "propertyName": "pathData",
          "startTime": 915,
          "endTime": 1025,
          "interpolator": "ACCELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 18 11 L 6 11 L 6 9 L 18 9 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 11 L 6.5 11 L 6.5 9 L 8.5 9 Z"
        },
        {
          "id": "464",
          "layerId": "449",
          "propertyName": "pathData",
          "startTime": 1025,
          "endTime": 1100,
          "interpolator": "DECELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 11 L 6.5 11 L 6.5 9 L 8.5 9 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 17 11 L 15 11 L 15 9 L 17 9 Z"
        },
        {
          "id": "465",
          "layerId": "448",
          "propertyName": "pathData",
          "startTime": 965,
          "endTime": 1070,
          "interpolator": "ACCELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 18 8 L 6 8 L 6 6 L 18 6 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 8.5 8.5 L 6.5 8.5 L 6.5 6.5 L 8.5 6.5 Z"
        },
        {
          "id": "466",
          "layerId": "448",
          "propertyName": "pathData",
          "startTime": 1070,
          "endTime": 1100,
          "interpolator": "DECELERATE",
          "type": "path",
          "fromValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9 11 L 7 11 L 7 9 L 9 9 Z",
          "toValue": "M 0 0 L 0 24 L 24 24 L 24 0 Z M 9 11 L 7 11 L 7 9 L 9 9 Z"
        }
      ]
    }
  }
}

**Comment by alexjlockwood** [comment]
This should be fixed now! I tested your project and exporting to SVG and SVG spritesheet both worked as expected. Thanks for reporting!

I will deploy the fix to https://shapeshifter.design hopefully by the end of the day. 

More info on the fix here: https://gist.github.com/alexjlockwood/b74fc1be361d041867ae8118ef4806fa?short_path=a2093ca

**Comment by alexjlockwood** [comment]
I just deployed a fix at https://shapeshifter.design

Let me know if it works for you!
