### ISSUE TITLE
Path distortion

### ISSUE THREAD

**Issue by Shiwoen** [alexjlockwood/ShapeShifter#255]
When importing the following SVG (generated from Adobe Illustrator), the path appears distorted.
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 72.367 46.964">
  <title>Asset 1</title>
  <path d="M54,9.422c-6.555,6.043-13.558,13.787-17.812,22.27C31.93,23.209,24.926,15.465,18.372,9.422a101.486,101.486,0,0,0,17.811,1.564A101.5,101.5,0,0,0,54,9.422M72.367,0A96.572,96.572,0,0,1,36.183,6.986,96.567,96.567,0,0,1,0,0S36.183,23.482,36.183,46.964C36.183,23.482,72.367,0,72.367,0Z"/>
</svg>
```

**Comment by alexjlockwood** [comment]
Thank you for reporting! I was able to reproduce the issue. Seems like you found a bug in my path parsing logic. :)

Expected:

<img width="689" alt="screen shot 2018-05-04 at 1 50 58 pm" src="https://user-images.githubusercontent.com/1380747/39652404-46a01d48-4fa2-11e8-93f4-5033f2960210.png">

Actual:

<img width="866" alt="screen shot 2018-05-04 at 1 51 07 pm" src="https://user-images.githubusercontent.com/1380747/39652407-4a82a2be-4fa2-11e8-9de0-86b62aa04043.png">

**Comment by alexjlockwood** [comment]
Could possibly be related to a previously reported bug: https://github.com/alexjlockwood/ShapeShifter/issues/218

**Comment by alexjlockwood** [comment]
I'll find some time to fix these bugs over the weekend. Sorry about that! I have mainly been testing SVG import with SVGs created by Sketch... not as much Illustrator. I guess I should test that out more...

**Comment by alexjlockwood** [comment]
I just deployed a fix at https://shapeshifter.design

Let me know if it works for you!
