### ISSUE TITLE
Allow to add another animation step if it fits exactly with the remain time

### ISSUE THREAD

**Issue by BraisGabin** [alexjlockwood/ShapeShifter#261]
You can reproduce this issue easily: 
- Open ShapeShifer with an empry state. 
- Add an alpha animation
- Add two more animation "steps"

You are not going to be able to add the third "step". It fits exactly, but you can't add it.

The workaround is to change the animation duration to 301ms.

**Comment by alexjlockwood** [comment]
Ahh, thanks for reporting. Will get on it!

Honestly, the better solution might be to extend the animation duration automatically... so that the animation grows to make the new animation blocks fit.

**Comment by BraisGabin** [comment]
Yes, that will be even better! Mean while, an alert could be usefull to point out why that button doesn't work. Right now you must to figure it out.

**Comment by alexjlockwood** [comment]
I created a separate bug to track the expanding animation duration feature request here: https://github.com/alexjlockwood/ShapeShifter/issues/262
