### ISSUE TITLE
Color change animation

### ISSUE THREAD

**Issue by Astralgr** [alexjlockwood/ShapeShifter#299]
Besides  rotation, scale, pivot and translate do you consider adding also a color change animation ?

**Comment by alexjlockwood** [comment]
You should be able to do that by animating either the `fillColor` or `strokeColor` property of a path:

<img width="424" alt="screen shot 2018-07-23 at 10 57 19 am" src="https://user-images.githubusercontent.com/1380747/43094255-3b648de8-8e67-11e8-826f-efdc224dcacf.png">

**Comment by alexjlockwood** [comment]
Click "File --> Demo" and select "Morphing animals" for an example animation that animates the `fillColor` property of a path.

**Comment by alexjlockwood** [comment]
Closing the issue, but feel free to reopen if I misinterpreted your question or if I wasn't 100% clear!

**Comment by Astralgr** [comment]
Exactelly what I needed and sorry for wasting your time.

Thank you so much for your hard work on this tool !

**Comment by alexjlockwood** [comment]
No problem! And it's OK... I have plans to improve the documentation for this...
