### ISSUE TITLE
AnimatedVectorDrawable export not animating Galaxy S7 8.0.0

### ISSUE THREAD

**Issue by ersin-ertan** [alexjlockwood/ShapeShifter#300]
After exporting the AnimatedVectorDrawable and upon running, only first frame shows, onAnimationStart and onAnimationEnd are called in quick succession, but the animation does not appear on screen.

```kotlin
with(findViewById<AppCompatImageView>(R.id.my_avd).drawable){
                if(this is AnimatedVectorDrawable){
                    registerAnimationCallback(object: Animatable2.AnimationCallback() {
                        override fun onAnimationStart(drawable: Drawable?) {
                            super.onAnimationStart(drawable)
                        }
                        override fun onAnimationEnd(drawable: Drawable?) {
                            super.onAnimationEnd(drawable)
                        }
                    })
                    start()
                }
            }
```
```
targetSdkVersion 28
compileSdkVersion 28
minSdkVersion 26
implementation 'androidx.vectordrawable:vectordrawable-animated:1.0.0-beta01'
implementation 'androidx.appcompat:appcompat:1.0.0-beta01'
```
Testing device: Android 8.0.0 Samsung Galaxy S7
Shapeshifter and AnimatedVectorDrawable export file attached: [myAvdAndShapshifter.zip](https://github.com/alexjlockwood/ShapeShifter/files/2220425/myAvdAndShapshifter.zip)

**Comment by alexjlockwood** [comment]
I think you may need to use `if (this is AnimatedVectorDrawableCompat)` instead?

**Comment by ersin-ertan** [comment]
I've tried both, the `if` only continues with `AnimatedVectorDrawable`. Both `registerAnimationCallback` and `start` are called, which then calls `onAnimationStart/End`. I've also moved `start` into a button click, and `onAnimationStart/End` is still called one after each other.

**Comment by alexjlockwood** [comment]
Are you setting the drawable in XML using `app:srcCompat="@drawable/my_avd"`?

**Comment by alexjlockwood** [comment]
Can you import this sample project and try it out? The animation plays fine for me...
[VectorSample.zip](https://github.com/alexjlockwood/ShapeShifter/files/2221033/VectorSample.zip)

**Comment by alexjlockwood** [comment]
What do you mean by "pre click left" and "post right - no animation"?

**Comment by ersin-ertan** [comment]
Image on the left is before I clicked on the content. Image on the right is
after I clicked on the content. Animation does not start or play, it
switches from left image to right image in a single frame.

**Comment by ersin-ertan** [comment]
Since the animation is working for you with regards to the VectorSample but not for me, then the diff is the hardware. This is a problem outside the scope of Shapeshifter, no?

**Comment by alexjlockwood** [comment]
Yeah pretty much...

Do you have another device to test with? Maybe try it with the emulator? I really have no clue why it isn't working for you...

**Comment by ersin-ertan** [comment]
It may be concerning that the animation is not playing correctly on test phone: https://youtu.be/nsDxiwWqc6Q

**Comment by ersin-ertan** [comment]
lg optimus l9 p769 - Android 4.1.2

**Comment by alexjlockwood** [comment]
I mean... to be honest it sounds like you may have found a bug in the support library at this point. :|

**Comment by ersin-ertan** [comment]
Ok thanks Alex and sorry to bother you about this within ShapeShifter.
Reproduced; the 4.1 emulator performed exactly the same as the LG Optimus L9 P769 device.

**Comment by alexjlockwood** [comment]
Do you mind if I use your `AnimatedVectorDrawable` as an example in my bug report to Google? I can replace the paths with random shapes if you like.

**Comment by ersin-ertan** [comment]
Feel free to use it as is

**Comment by alexjlockwood** [comment]
Filed! https://issuetracker.google.com/issues/111780277

**Comment by ersin-ertan** [comment]
I had turned my animations off long ago to conserve battery, and today was the first time they have been turned on; animations are working. At least a bug report for another issue came out of this :+1:
