### ISSUE TITLE
Rotate around center?

### ISSUE THREAD

**Issue by johnknoop** [alexjlockwood/ShapeShifter#337]
Rotations behave a bit weirdly since the groups don't rotate around their center points. Is there any way to accomplish that, or maybe define the transport origin?

Otherwise, great tool!

**Comment by alexjlockwood** [comment]
It should be possible if you set the pivotX and pivotY properties on the group (by default they are set to 0).

**Comment by johnknoop** [comment]
Works great. Thanks!
