### ISSUE TITLE
Can't export Animated Vector Drawable

### ISSUE THREAD

**Issue by fabbiogi** [alexjlockwood/ShapeShifter#350]
Hello there, 
I'm making an icon animation for Android splash page, using some nested elements and masks, the result is really fine, but when coming to export fails to save as animated vector drawable.
I'm clicking on the menu option for export animated xml and just does nothing, working with Firefox and Safari on Mac
Trying to export the non-animated xml works fine.
Is maybe too complex, or with too many nested emelents?

Another animation, without masks gets exported just fine.

That's the setting I used:
<img width="778" alt="Schermata 2021-12-23 alle 19 32 17" src="https://user-images.githubusercontent.com/96593219/147279574-a4746701-c18d-4e88-aa75-860b61f8baa4.png">

**Comment by imashnake0** [comment]
@fabbiogi It doesn't export it if you have hidden elements for some reason, as a workaround you can set fillAlpha to 0 for elements that you want to hide.

**Comment by fabbiogi** [comment]
@imashnake0 you're right, export goes well now, thanks a lot!
I've changed my animation meanwhile but is good to know it.
Cheers
