### ISSUE TITLE
feature request: make SVG -> vector drawable portion standalone

### ISSUE THREAD

**Issue by kaushikgopal** [alexjlockwood/ShapeShifter#48]
It would be super helpful to have the logic that converts an SVG -> Vector Drawable asset standalone. 

While Android Studio currently has a Vector Asset Studio tool, in practice I've found that it doesn't support all of the SVG features. 

We could greatly benefit from the convenience of an open source web tool and one that handles Animated Vector Drawables... like ShapeShifter 😄

for more context: https://twitter.com/kaushikgopal/status/836573683825045506

**Comment by alexjlockwood** [comment]
FYI... somewhat related... v0.1.2 will now export standalone vector drawables in addition to AVDs and SVGs.

**Comment by alexjlockwood** [comment]
FYI, I think v1.0 (to be released hopefully next Monday) will probably be as close as I'll get to a 'stand alone SVG-to-VD' feature. Basically the workflow will be the same as Android Icon Animator (https://romannurik.github.io/AndroidIconAnimator/)... you import the SVGs as layers and immediately export them as VectorDrawables.

Going to close for now but feel free to reopen after v1.0 is released if you have anything else to clarify. :)
