### ISSUE TITLE
Import does not work in Firefox Nightly

### ISSUE THREAD

**Issue by nt1m** [alexjlockwood/ShapeShifter#69]
Doesn't work in developer edition either.

**Comment by alexjlockwood** [comment]
Could you please post the SVG that you tried to import and/or describe what happened when you tried to import?

Does it work in the normal Firefox or does it also not work in that too?

**Comment by nt1m** [comment]
Here are the two SVGs:
https://hostr.co/z2t745iPBtsD
https://hostr.co/3C2A2dBivEZm

**Comment by nt1m** [comment]
Absolutely nothing happens when I choose the two files

here's my console errors:
<img width="1203" alt="console-svg-shifter" src="https://cloud.githubusercontent.com/assets/1795135/23581778/57b72434-0113-11e7-8ba2-17badacfd55b.png">

**Comment by nt1m** [comment]
@alexjlockwood Doesn't work on Firefox stable 51.0.1 either. Same errors.

**Comment by alexjlockwood** [comment]
Thanks for the SVGs! The same behavior occurs for me on Firefox, but strangely enough things seem to import fine on Chrome. Will take a look!

**Comment by alexjlockwood** [comment]
The crash should be fixed now. LMK if you still have any issues!

**Comment by nt1m** [comment]
Works great, thanks! :+1:

**Comment by alexjlockwood** [comment]
NP, let me know if you encounter any other issues! SVG import === hard. :)

**Comment by alexjlockwood** [comment]
(Also sorry in advance if there are some glitches in Firefox that aren't present in other browsers. I'm somewhat new to this whole web development thing and haven't done much testing outside of Chrome yet.)

**Comment by alexjlockwood** [comment]
Things seem to be a bit jankier in Firefox than in Chrome too (especially when you move the mouse around a lot while animations are running). Filed what I suspect to be the problem separately here: #70
